{{- if .Values.components.auth.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: horusec-auth
  name: auth
  namespace: horusec
spec:
  ports:
  {{- range $key, $value := .Values.components.auth.port }}
    - name: {{ $key }}
      port: {{ $value }}
      protocol: TCP
      targetPort: {{ $key }}
  {{- end }}
  selector:
    app: horusec-auth
  type: ClusterIP
{{- end }}