apiVersion: v1
kind: Service
metadata:
  labels:
    app: horusec-manager
  name: manager
  namespace: horusec
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: http
  selector:
    app: horusec-manager
  type: ClusterIP
