// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package horusec

import (
	"github.com/ZupIT/horusec-operator/internal/horusec/usecase"
)

// Injectors from wire.go:

func NewAdapter(client usecase.KubernetesClient, builder usecase.ResourceBuilder) *Adapter {
	autoscaling := usecase.NewAutoscaling(client, builder)
	databaseMigrations := usecase.NewDatabaseMigrations(client, builder)
	deployments := usecase.NewDeployments(client, builder)
	deploymentsAvailability := usecase.NewDeploymentsAvailability(client)
	ingressRules := usecase.NewIngressRules(client, builder)
	currentState := usecase.NewCurrentState(client)
	serviceAccounts := usecase.NewServiceAccounts(client, builder)
	services := usecase.NewServices(client, builder)
	unavailabilityReason := usecase.NewUnavailabilityReason(client)
	adapter := &Adapter{
		Autoscaling:             autoscaling,
		DatabaseMigrations:      databaseMigrations,
		Deployments:             deployments,
		DeploymentsAvailability: deploymentsAvailability,
		IngressRules:            ingressRules,
		CurrentState:            currentState,
		ServiceAccounts:         serviceAccounts,
		Services:                services,
		UnavailabilityReason:    unavailabilityReason,
	}
	return adapter
}
