// Copyright 2020 ZUP IT SERVICOS EM TECNOLOGIA E INOVACAO SA
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package messages

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"

	"github.com/ZupIT/horusec-operator/internal/entities/groupversion"
)

// EDIT THIS FILE!  THIS IS SCAFFOLDING FOR YOU TO OWN!
// NOTE: json tags are required.  Any new fields you add must have json tags for the fields to be serialized.

// HorusecMessagesSpec defines the desired state of HorusecMessages
type HorusecMessagesSpec struct {
	// INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
	// Important: Run "make" to regenerate code after modifying this file

	// Foo is an example field of HorusecMessages. Edit horusecmessages_types.go to remove/update
	Foo string `json:"foo,omitempty"`
}

// HorusecMessagesStatus defines the observed state of HorusecMessages
type HorusecMessagesStatus struct {
	// INSERT ADDITIONAL STATUS FIELD - define observed state of cluster
	// Important: Run "make" to regenerate code after modifying this file
}

//+kubebuilder:object:root=true
//+kubebuilder:subresource:status

// HorusecMessages is the Schema for the horusecmessages API
type HorusecMessages struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   HorusecMessagesSpec   `json:"spec,omitempty"`
	Status HorusecMessagesStatus `json:"status,omitempty"`
}

//+kubebuilder:object:root=true

// HorusecMessagesList contains a list of HorusecMessages
type HorusecMessagesList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []HorusecMessages `json:"items"`
}

//nolint
func init() {
	groupversion.SchemeBuilder.Register(&HorusecMessages{}, &HorusecMessagesList{})
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HorusecMessages) DeepCopyInto(out *HorusecMessages) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HorusecMessages.
func (in *HorusecMessages) DeepCopy() *HorusecMessages {
	if in == nil {
		return nil
	}
	out := new(HorusecMessages)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HorusecMessages) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HorusecMessagesList) DeepCopyInto(out *HorusecMessagesList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HorusecMessages, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HorusecMessagesList.
func (in *HorusecMessagesList) DeepCopy() *HorusecMessagesList {
	if in == nil {
		return nil
	}
	out := new(HorusecMessagesList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HorusecMessagesList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HorusecMessagesSpec) DeepCopyInto(out *HorusecMessagesSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HorusecMessagesSpec.
func (in *HorusecMessagesSpec) DeepCopy() *HorusecMessagesSpec {
	if in == nil {
		return nil
	}
	out := new(HorusecMessagesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HorusecMessagesStatus) DeepCopyInto(out *HorusecMessagesStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HorusecMessagesStatus.
func (in *HorusecMessagesStatus) DeepCopy() *HorusecMessagesStatus {
	if in == nil {
		return nil
	}
	out := new(HorusecMessagesStatus)
	in.DeepCopyInto(out)
	return out
}
